---
- hosts: all
  become: yes

  pre_tasks:
    - name: Install postgresql
      apt:
       name: postgresql-14
       update_cache: yes
      

    - name: Install required packages
      apt:
        name:
          - wget
          - python3-psycopg2
          - acl
        state: latest

    - name: Check if PostgreSQL is initialized
      ansible.builtin.stat:
        path: "/etc/postgresql/14/main/pg_hba.conf"
      register: postgres_data

    - name: Empty data dir
      ansible.builtin.file:
        path: "/etc/postgresql/14/main/"
        state: absent
      when: not postgres_data.stat.exists

    - name: Initialize PostgreSQL
      ansible.builtin.shell: "/usr/lib/postgresql/14/bin/initdb -D /etc/postgresql/14/main/"
      become: true
      become_user: postgres
      when: not postgres_data.stat.exists
    
    # - name: "Initialize PostgreSQL"
    #   shell: /usr/lib/postgresql/14/bin/postgresql-14-setup initdb
    #   when: not postgres_data.stat.exists


    - name: Start and enable service
      service:
        name: postgresql
        state: started
        enabled: true

    # - name: "Start and enable services"
    #   service: 
    #     name: postgresql-14
    #     state: started

    # - name: Allow PostgreSQL database service
    #   firewalld:
    #     service: postgresql
    #     permanent: yes
    #     state: enabled

    - name: "Create app database"
      postgresql_db:
        state: present
        name: "jumia_phone_validator"
      become: yes
      become_user: postgres

    - name: "Create db user"
      postgresql_user:
        state: present
        name: "jumia"
        password: "jumia"
      become: yes
      become_user: postgres

    - name: "Grant db user access to app db"
      postgresql_privs:
        type: database
        database: "jumia_phone_validator"
        roles: "jumia"
        grant_option: no
        privs: all
      become: yes
      become_user: postgres

    - name: "Allow md5 connection for the db user"
      postgresql_pg_hba:
        dest: "/etc/postgresql/14/main/pg_hba.conf"
        contype: host
        databases: all
        method: md5
        users: all
        source: 10.10.4.126
        create: true
      become: yes
      become_user: postgres
      notify: restart postgres
 
    # - name: "Load SQL script into a variable"
    #   set_fact:
    #     migration_sql: "{{ lookup('file', 'database/sample.sql') }}"

    - name: Copying sql data dump
      copy:
        src: "templates/sample.sql"
        dest: "/tmp/sample.sql"
        mode: "0644"

    - name: "Execute script from variable"
      command: "psql -d jumia_phone_validator -f /tmp/sample.sql"
      become_user: postgres
      register: sql_response_variable
      notify: restart postgres

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted
       

