version: '3.8'
services:
    frontend:
         image: validator-frontend
         build:
          context: validator-frontend
          dockerfile: ../validator-frontend/Dockerfile
         ports:
           - "8081:80"
         depends_on:
           - backend
         networks:
           - validator
       
    backend:
         image: validator-backend
         build:
            context: validator-backend
            dockerfile: Dockerfile
         ports:
            - "8080:8080"
         networks:
            - validator
networks:
    validator: